spring.application.name=shoptech

#permito que hibernate cree las tablas ante de ejecutar el data.sql
spring.jpa.defer-datasource-initialization=true

#siempre se ejecuta data.sql usa INSERT IGNORE asi que es seguro correrlo en cada arranque
spring.sql.init.mode=always

#configuracion
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}

#configuracion jwt
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}

#configuracion para swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.persist-authorization=true

#configuracion para cloudinary
cloudinary.cloud.name=${CLOUD_NAME}
cloudinary.api.key=${CLOUD_KEY}
cloudinary.api.secret=${CLOUD_SECRET}